
# Project Makefile for Assembler and Simulator

# =========================
# Configuration
# =========================
CC        = gcc
CFLAGS    = -Wall -Wextra -std=c99
LDFLAGS   =
INC_DIR   = include
BIN_DIR   = bin
PREFIX    = /usr/local

# Source files
ASSEMBLER_SRC    = assembler/assembler.c common/string_utils.c
SIMULATOR_SRCS   = simulator/simulator.c simulator/instruction_handlers.c simulator/trap_handlers.c common/string_utils.c
DISASSEMBLER_SRC = disassembler/disassembler.c

# Output binaries
ASSEMBLER_BIN    = $(BIN_DIR)/pasm
SIMULATOR_BIN    = $(BIN_DIR)/pvm
DISASSEMBLER_BIN = $(BIN_DIR)/pdis

# =========================
# Default Target: standard build
# =========================
.PHONY: all
all: $(BIN_DIR) $(ASSEMBLER_BIN) $(SIMULATOR_BIN) $(DISASSEMBLER_BIN)
	@echo "**Build Complete (Standard)**"

# =========================
# Release build (optimized)
# =========================
.PHONY: release
release: CFLAGS += -DNO_LOG -O3 -march=native -flto -funroll-loops -pipe
release: all
	@echo "**Build Complete (Release mode)**"

# =========================
# Benchmark build (timed)
# =========================
.PHONY: benchmark
benchmark: CFLAGS += \
	-DBENCHMARK \
	-DHIDE_TRACE \
	-O3 -march=native -mtune=native \
	-flto -funroll-loops -fomit-frame-pointer \
	-fno-stack-protector -pipe
benchmark: all
	@echo "**Build Complete (Benchmark mode)**"

# =========================
# Debug build (no optimization, debug info)
# =========================
.PHONY: debug
debug: CFLAGS += -g -O0
debug: all
	@echo "**Build Complete (Debug mode)**"

# =========================
# Create the bin directory if it doesn't exist
# =========================
$(BIN_DIR):
	@mkdir -p $(BIN_DIR)

# =========================
# Assembler Compilation
# =========================
$(ASSEMBLER_BIN): $(ASSEMBLER_SRC)
	$(CC) $(CFLAGS) -I$(INC_DIR) $^ -o $@ $(LDFLAGS)
	@echo "Built $(ASSEMBLER_BIN)"

# =========================
# Simulator Compilation
# =========================
$(SIMULATOR_BIN): $(SIMULATOR_SRCS)
	$(CC) $(CFLAGS) -I$(INC_DIR) $^ -o $@ $(LDFLAGS)
	@echo "Built $(SIMULATOR_BIN)"

# =========================
# Disassembler Compilation
# =========================
$(DISASSEMBLER_BIN): $(DISASSEMBLER_SRC)
	$(CC) $(CFLAGS) -I$(INC_DIR) $^ -o $@ $(LDFLAGS)
	@echo "Built $(DISASSEMBLER_BIN)"

# =========================
# Install/Uninstall
# =========================
.PHONY: install
install: all
	@echo "Installing to $(PREFIX)/bin..."
	@install -d $(DESTDIR)$(PREFIX)/bin
	@install -m 755 $(ASSEMBLER_BIN) $(DESTDIR)$(PREFIX)/bin
	@install -m 755 $(SIMULATOR_BIN) $(DESTDIR)$(PREFIX)/bin
	@install -m 755 $(DISASSEMBLER_BIN) $(DESTDIR)$(PREFIX)/bin
	@echo "**Installation Complete**"

.PHONY: uninstall
uninstall:
	@echo "Uninstalling from $(PREFIX)/bin..."
	@rm -f $(DESTDIR)$(PREFIX)/bin/pasm
	@rm -f $(DESTDIR)$(PREFIX)/bin/pvm
	@rm -f $(DESTDIR)$(PREFIX)/bin/pdis
	@echo "**Uninstallation Complete**"

# =========================
# Clean target
# =========================
.PHONY: clean
clean:
	@echo "Cleaning project..."
	@rm -rf $(BIN_DIR)
	@rm -f a.out.bin # Remove the output file generated by the assembler
	@echo "**Clean Complete**"

# =========================
# Usage notes:
# make all        # Standard build
# make release    # Optimized release build
# make benchmark  # Optimized + timing instrumentation
# make debug      # Debug build with symbols, no optimization
# make clean      # Remove binaries and output files
# make install    # Install binaries system-wide (requires root)
# make uninstall  # Remove installed binaries (requires root)
# =========================
